//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMWG_MVCApp_Profile.DB_1
{
    using System;
    
    public enum Cinsiyet : int
    {
        None = 0,
       Erkek = 1,
        Kadın = 2
    }
}


