//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace KMWG_MVCApp_Profile.DB_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    public partial class MvgMvcDBEntities : DbContext
    {
        public MvgMvcDBEntities()
            : base("name=MvgMvcDBEntities")
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserGroup> UserGroup { get; set; }
    }
}
